project:
  type: book

book:
  title: "Advanced Engineering Mathematics"
  chapters:
    - index.qmd
    - chapters/contents.qmd
    - chapters/ch1.qmd
    - chapters/ch5.qmd
    - chapters/ch6.qmd
    - chapters/intro.qmd


format:
  html:
    theme: cosmo