project:
  type: book

book:
  title: "Advanced Engineering Mathematics"
  chapters:
    - index.qmd
    - chapters/contents.qmd
    - chapters/01-first-order-odes.qmd
    - chapters/intro.qmd


format:
  html:
    theme: cosmo