project:
  type: book

book:
  title: "Advanced Engineering Mathematics"
  chapters:
    - index.qmd
    - chapters/contents.qmd
    - chapters/ch1.qmd
    - chapters/ch2.qmd
    - chapters/ch3.qmd
    - chapters/ch4.qmd
    - chapters/ch5.qmd
    - chapters/ch6.qmd
    - chapters/ch7.qmd
    - chapters/ch8.qmd
    - chapters/ch9.qmd
    - chapters/ch10.qmd
    - chapters/ch17.qmd
    - chapters/ch18.qmd
    - chapters/ch19.qmd
    - chapters/ch20.qmd
    - chapters/ch21.qmd
    - chapters/ch22.qmd
    - chapters/ch23.qmd
    - chapters/intro.qmd
    


format:
  html:
    theme: cosmo